# server config
server:
  port: 8088
spring:
  # json
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # datasource
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_boot_demo?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    # 使用的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 1000
# mybatis
mybatis:
# 从src/main/resource开始
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  # 实体类的别名
  type-aliases-package: com.wxss.demo.entity
  config-location: mybatis/mybatis-config.xml


